name: stock
channels:
  - plotly
  - weinbe58
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h4abf009_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py37h06a4308_2
  - cffi=1.14.4=py37h261ae71_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.3=pyhd3eb1b0_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h7ca028e_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py37h10f8cd9_2
  - icu=67.1=he1b5a44_0
  - importlib-metadata=3.4.0=py37h89c1867_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - ipykernel=5.4.3=py37h888b3d9_0
  - ipython=7.20.0=py37h888b3d9_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py37hc928c03_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - llvmlite=0.31.0=py37hd408876_0
  - markupsafe=1.1.1=py37hb5d75c8_2
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37h1d35a4c_1
  - mistune=0.8.4=py37h4abf009_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py37h89c1867_0
  - numba=0.48.0=py37h0573a6f_0
  - numexpr=2.7.2=py37hb2eb853_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - omp=1.0=0
  - openssl=1.1.1m=h7f8727e_0
  - pandas=1.1.3=py37he6710b0_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.3.3=py37h06a4308_0
  - plotly=5.6.0=py_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.14=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h4abf009_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyzmq=20.0.0=py37h5a562af_1
  - readline=8.1=h27cfd23_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2020.3=hfd86e86_0
  - tenacity=8.0.1=py37h06a4308_0
  - terminado=0.9.2=py37h89c1867_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h4abf009_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - charset-normalizer==2.0.12
    - idna==3.3
    - inflection==0.5.1
    - lxml==4.8.0
    - more-itertools==8.12.0
    - multitasking==0.0.10
    - nasdaq-data-link==1.0.1
    - packaging==21.3
    - patsy==0.5.2
    - requests==2.27.1
    - scipy==1.7.3
    - simplejson==3.17.6
    - statsmodels==0.13.2
    - urllib3==1.26.8
    - yfinance==0.1.70
prefix: /home/user/miniconda3/envs/stock
